name: Main Taski workFlow

on:
  push:
    branches:
      - main


jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.10

        env:
          POSTGRES_USER: beba_la_bobins
          POSTGRES_PASSWORD: beba
          POSTGRES_DB: beba_database
        
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Set up phython
        uses: actions/setup-python@v4
        with:
          python-vesion: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8==6.0.0 flake8-isort==6.0.0
          pip install -r ./backend/requirements.txt
      - name: Test with flak8 and django teeests
        env:
          POSTGRES_USER: beba_la_bobins
          POSTGRES_PASSWORD: beba
          POSTGRES_DB: beba_database
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
        run: |
          python -m flake8 backend/
          cd backend/
          python manage.py test